### ISSUE TITLE
[HTTPD] Spawning thread fails on VS2017

### ISSUE THREAD

**Issue by wipe2238** [rotators/sfall#2]
If .dll is compiled with VS2017+v140_xp (as it should be for mod releases), attempt to spawn HTTPD thread (with `std::thread()`) locks the process forever for whatever reason.

If .dll is compiled with VS2019+v142 (as it is done for testing), everything seems to work fine.

This is currently veeery low priority, as HTTPD is not intended to be used by players anyway, nor worth sharing with other modders in current state. When/if it changes some day, it can be looked at again.

**Comment by ghost2238** [comment]
Might be worth retrying on VS2017+v140_xp now since changing to use CreateThread instead of std::thread.

**Comment by wipe2238** [comment]
Looks fine for me.

I'd get rid of ddraw.rotators.ini from mod repo and leave submodule compiled into v140_xp.

**Comment by wipe2238** [comment]
OK, not so fine :P

With HTTPD on, saving game over existing slot leads to crash, probably here
https://github.com/rotators/sfall/blob/73d6d644cb00cec4124fe72437230f3168705212/sfall/Modules/Rotators.HTTPD.cpp#L72
Even more reason to get rid of ddraw.rotators.ini :>

**Comment by ghost2238** [comment]
Classical case of forgetting to check for null ptr on handle, oh well, let's hope there's not any more crashes...

**Comment by wipe2238** [comment]
We'll see about that :> Closing anyway, as both original problem and .ini are gone now.
