### ISSUE TITLE
Run script function passing argument without using hookscript

### ISSUE THREAD

**Issue by wipe2238** [rotators/sfall#3]
For DIALOGOUT_YESNO, see e627ebe

`dialog_out_` is non-blocking, so proc below will run fully and there's no way to return pressed key/button back to script at this stage
```pascal
procedure test
begin
    sfall_func2("r_message_box", "question?", 0x10);
    display_msg("some spam");
end
```
And that makes sense - after `ctrl+x` game doesn't freeze after all.

Hooks added in commit should be fine; they takes care of catching user input when it finally happens, and should be ready to pass result to scripts No messing with engine code along the way, yay.
"Only" problem here is i have no idea how to call script proc with argument "out of nowhere". Hookscripts have hardly any sense here - why question in one script should be passed to other script(s)?

Instead, i wanted to use message box like that...
```pascal
// TODO add Y/y/N/n
#define DIALOGOUT_YES(input) (input == 13 or input == 244) // enter || YES button
#define DIALOGOUT_NO(input)  (input == 245) // NO button
#define DIALOGOUT_ESC(input) (input == 27)

procedure callback_func(variable input)
begin
    display_msg("input = " + input);

    if(DIALOGOUT_YES(input)) then 
        display_msg("Yay!");
    else if(DIALOGOUT_NO(input)) then
        display_msg("Oh noes!");
    else if(DIALOGOUT_ESC(input)) then
        display_msg("Ugh.");
    else
        display_msg("unknown input<" + input +">" );
end

procedure show_message
begin
    sfall_func5("r_message_box", "question?", 0x10, 143, 143, "callback_func");
end
```
...but i'm stuck here:
https://github.com/rotators/sfall/blob/e627ebef2627502ff25ecf1dedcdfb12ef4cfaae/sfall/Modules/Rotators.Script.cpp#L148-L150

**Comment by FakelsHub** [comment]
Why do you need this?
 To do this, there are user interface functions where you can create a similar dialog box using a couple of functions

**Comment by FakelsHub** [comment]
I would do this:
```js
while (result == 0) then begin
   result = r_message_box()
end
// check result
```

For callback procedures you need a make separate opcode function for the compiler.

**Comment by FakelsHub** [comment]
What purpose do you pursue from your Rotators code in sfall.  ?  Besides the fact that you help me with ideas with implementations.
 Maybe you want to make an analogue of the new HRP with open source code?  :-)

**Comment by FakelsHub** [comment]
parameter can be transmitted through the structure for scripts
`overrideScriptStruct.fixedParam->fixed_param = timedEvent;`
and getting it using the function `fixed_param`

**Comment by FakelsHub** [comment]
parameter can be passed through the structure for scripts
example: `overrideScriptStruct.fixedParam = timedEvent;`
and getting it using the function `fixed_param`

**Comment by wipe2238** [comment]
> Why do you need this?
> To do this, there are user interface functions where you can create a similar dialog box using a couple of functions

[Science](https://www.smbc-comics.com/?id=1202), of course ;)
`dialog_out_` is small enough to toy with it while learning how engine works under the hood... and bit of asm along the way to understand that. I've never messed with engine or sfall before, so i'd rather waste time to find missing info, get rid of `create_message_window` limitations, and expose it all to scripts. If it's good enough and will be part of official sfall some day, that's great, it can be useful for quick gl scripts (without need to mess with UI or config files first, or recompiling/deleting before loading to turn them on/off). And if not, i still learned some stuff here and there, which gonna help with other things i'd want to check in future.
 
> What purpose do you pursue from your Rotators code in sfall. ?

Making stuff happen.
Except for some parts (which we know will never be used by anyone else), if things we add here are later added to official sfall - that way or another - and still works as we want them, that's awesome. Repo is more like a staging area from where sfall veterans can take than its own thing with specific goal - and that's also why i try to to keep our changes clearly separated from regular sfall code when possible, so they're always easy to find. Feels like that's the way NovaRain wants things to go, instead of  regular PRs.

In the end of the day, we just want our scripts without missing minor features, that's all. If it requires setting whole repo for it, so be it :>

---

> parameter can be passed through the structure for scripts
> and getting it using the function `fixed_param`

Ohh, looks like that's what i was looking for, gotta check it later; thanks! :)

**Comment by wipe2238** [comment]
Yup, that was exactly the part i was missing :)
```pascal
procedure answer
begin
    if(fixed_param) then
        display_msg("Come on, let's go and play! :D");
    else
        display_msg("Okay, bye ;_;");
end

procedure question
begin
    sfall_func5("r_message_box", "Do you wanna build a snowman?", 0x10, 145, 145, @answer);
end
```
